### ISSUE TITLE
Inconsistency between release tags names and release artifacts names

### ISSUE THREAD

**Issue by tony-engineering** [helmwave/helmwave#1031]
**Describe the bug**

When I do 
```
➜  helmwave git:(main) TAG_NAME=$(curl https://api.github.com/repos/helmwave/helmwave/releases/latest | jq -r .tag_name)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 41279    0 41279    0     0  68506      0 --:--:-- --:--:-- --:--:-- 68456
➜  helmwave git:(main) echo $TAG_NAME 
v0.41.1
```
I expect that the following would download the corresponding release artifact
```
➜  helmwave git:(main) ✗ curl -L https://github.com/helmwave/helmwave/releases/download/${TAG_NAME}/gitops_${TAG_NAME}_linux_amd64.tar.gz -o helmwave.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     21      0 --:--:-- --:--:-- --:--:--    21
```
but it doesn't because the name of artifacts doesn't the `v` prefix.

**General info (please complete the following information):**

- Linux Debian

**To Reproduce**

See description.

**Expected behavior**

```
➜  helmwave git:(main) ✗ curl -L https://github.com/helmwave/helmwave/releases/download/${TAG_NAME}/gitops_${TAG_NAME}_linux_amd64.tar.gz -o helmwave.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 32.6M  100 32.6M    0     0  2235k      0  0:00:14  0:00:14 --:--:-- 1960k
```
(Received value should be around 32MB)

**Screenshots / Stdout**
NA

**Additional context**

NA

**Comment by zhilyaev** [comment]
## Hi @tony-engineering ✋

1. It's not a bug 🐛
2. We don't mention that tag and artifact names should be identical 💁‍♂️
3. Containers use the same version as artifacts (for example ghcr.io/helmwave/helmwave:0.41.1)
4. Only the git tag has `v` prefix. 


### Why don't we drop `v` from the prefix for the git tag?
Cause golang expects this prefix for module versioning.
You can read about it here https://pkg.go.dev/golang.org/x/mod/semver
As you can see all go.mod use semver. When semver is unavailable for git tag. Gomod will use weird tag like that `0.0.0-20240806141605-e8a1dd7889d6`

**Comment by zhilyaev** [comment]
@tony-engineering you can use this bash pipeline 
```
TAG_NAME=$(curl https://api.github.com/repos/helmwave/helmwave/releases/latest | jq -r .tag_name | tr -d v)
```

**Comment by tony-engineering** [comment]
ok makes sense. now I can see than it's the same on doctl releases page https://github.com/digitalocean/doctl/releases
