### ISSUE TITLE
Exit with success when repositry not exists

### ISSUE THREAD

**Issue by ddelay2** [helmwave/helmwave#124]
When adding some external chart and do not describe his repository in helmwave.yml.tpl helmwave exit with success and exit code 0.

Debug logs contains:
[💩 aka ERROR]: 🗄 "cetic" not found 
[💩 aka ERROR]: ❌ failed to download "cetic/adminer" at version "0.1.6" (hint: running `helm repo update` may help)

Helmwave version 0.10.1

**Comment by zhilyaev** [comment]
It will be fixed 0.12.0
