### ISSUE TITLE
Installing releases to wrong namespace

### ISSUE THREAD

**Issue by r-mironov** [helmwave/helmwave#135]
**Describe the bug**

Helmwave installs the release to default namespace(or kubectl context namespace, if you permanently save the namespace via kubectl context) instead of installing to the specified(`planfile`) namespace. 

However the helm metadata(`helm.sh/release.v1`) installs to the specified namespace. If you manually set `.Release.namespace`:
```
namespace: {{ .Release.namespace }}
``` 
in the helm chart, everything goes smoothly

**Version**

- Helmwave Version - `0.12.1 or 0.12.0`

**To Reproduce**

1) Set namespace to the release in `helmwave.yml`
2) Build and Install via `helmwave build --> helmwave deploy`
3) Check that the chart was installed to default namespace instead of selected namespace

**Expected behavior**

Helmwave installs the release to selected namespace(which sets via `planfile`)

**Comment by zhilyaev** [comment]
```
func NewHelm(ns string) (*helm.EnvSettings, error) {
	env := helm.New()
	fs := &pflag.FlagSet{}
	env.AddFlags(fs)
	flag := fs.Lookup("namespace")
	err := flag.Value.Set(ns)
	if err != nil {
		return nil, err
	}

	return env, nil
}
```

 also https://github.com/helm/helm/issues/9790

**Comment by zhilyaev** [comment]
```go
func NewCfg(ns string) (*action.Configuration, error) {
	cfg := new(action.Configuration)
	helmDriver := os.Getenv("HELM_DRIVER")
	config := genericclioptions.NewConfigFlags(false)
	config.Namespace = &ns
	err := cfg.Init(config, ns, helmDriver, log.Debugf)
	if err != nil {
		return nil, err
	}

	return cfg, nil
}

```
