### ISSUE TITLE
Improve test coverage: pkg/kubedog

### ISSUE THREAD

**Issue by r3nic1e** [helmwave/helmwave#199]
Current coverage: 0%

**Comment by zhilyaev** [comment]
Current coverage: 44%

**Comment by r3nic1e** [comment]
> Current coverage: ? %

still 0%

**Comment by zhilyaev** [comment]
nice

**Comment by zhilyaev** [comment]
idk how to test kubedog

**Comment by r3nic1e** [comment]
We can leave this as-is, leave a note in documentation and close this issue @zhilyaev

**Comment by zhilyaev** [comment]
🥇
