### ISSUE TITLE
Add support for hiding resource in diff

### ISSUE THREAD

**Issue by r3nic1e** [helmwave/helmwave#257]
We have some resources that are big and always change. And we want to hide them in diff.

I guess the easiest way will be introducing some label or annotation and skipping entire resource if this annotation exists

**Comment by r3nic1e** [comment]
@derbeneviv Yeah, I didn't mean to change your proposal, just forgot about it.

So, combined proposal:
- Ignore resources with `helm.sh/hook: test` annotation
- Ignore resources with custom (`helmwave.dev/show-service-messages: true`?) annotation

**Comment by zhilyaev** [comment]
I think we should add the ability to pass the annotation through the helmwave variable. 

```
export HELMWAVE_DIFF_SKIP_ANNO='helm.sh/hook: test','helmwave.dev/skip-diff: true'
```

**Comment by r3nic1e** [comment]
@zhilyaev Looks not easy to use - you have to struggle with quotes

**Comment by derbeneviv** [comment]
also found a (possible) issue:  
when running helmwave build on a chart with hooks, a line `+ # ========= HOOKS ========` is appearing always:
```
vault, vault-agent-injector-cfg, MutatingWebhookConfiguration (admissionregistration.k8s.io) has changed:
...
        - operations: ["CREATE", "UPDATE"]
          apiGroups: [""]
          apiVersions: ["v1"]
          resources: ["pods"]
      failurePolicy: Ignore
+ # ========= HOOKS ========
```
