### ISSUE TITLE
How to access different Chart Version

### ISSUE THREAD

**Issue by jeremy-london** [helmwave/helmwave#288]
Working on improving the GitOps flow for our team using helmwave

Scenario:

Main branch is `Chart.yml` is at `1.0.30` and pushed to registry
>`helmwave build` pull from registry and build plan for 1.0.30 -- All is Good

We make a new feature on a branch `1-new-branch` and tag the `Chart.yml` to `1.1.0-rc.1` and helm push to our registry

How do we get the pipeline running on branch `1-new-branch` to pull from the registry at that specified version to build a planfile to be checked by a set of linters/etc?

**Comment by zhilyaev** [comment]
Do you use OCI for push your chart to registry? Or Is it a regular chart repository like chart-museum?

**Comment by zhilyaev** [comment]
I'm not entirely sure what the question is. But I'll try to give a small example. I hope it will be useful. 

```mermaid
graph LR
1.1.0-rc1 --> 1.1.0 --> main
```


```
helm cm-push mychart --version="$CI_BRANCH_NAME" chartmuseum
```


helmwave.yml.tpl

```yaml
releases:
  - name: my
     chart:
        name: chartmuseum/mychart
        version: $CI_BRANCH_NAME
```

Tell us more details about your git repositories with helm charts.

**Comment by zhilyaev** [comment]
You can also tell helmwave to pull charts from a local directory. And then you don't have to bind to versions in your CI.

**Comment by jeremy-london** [comment]
Thank you this was exactly what i was looking for :D
