### ISSUE TITLE
helm is in progress [take a look]

### ISSUE THREAD

**Issue by zhilyaev** [helmwave/helmwave#358]
**Is your feature request related to a problem? Please describe.**
Sometimes helm cannot finished process correctly, then you can face with helm `another operation (install/upgrade/rollback) is in progress`. 

**Describe the solution you'd like**
Yes. You can fix it with `helm rollback` or `helmwave rollback`.
But I think we need take a look for another way. 

**Describe alternatives you've considered**

- override behavior lock
- create custom lock

**Comment by Blobson** [comment]
It would be nice to have a parameter, for example `rollback_ongoing_release: true/false` which will automagically applly `helm rollback` in such cases.
