### ISSUE TITLE
global Store

### ISSUE THREAD

**Issue by webmalex** [helmwave/helmwave#368]
**Is your feature request related to a problem? Please describe.**
> Alexander Efimov:
добрый день! не увидел примеров в факах как правильнее организовать хранение общих констант для шаблонов переменных разных релизов при использовании Gomplate ...

> Alexander Efimov:
речь не про секреты

> Alexander Efimov:
а вещи типа используемого реджестри по умолчанию и подобное

> Alexander Efimov:
пока вижу только один способ - искуственно рендерить в store каждому релизу ...

> Dmitrii Zhiliaev:
просто создать файл с общими валуес и дать его каждому релизу   releases: - name: foo    values:    - common.yaml    - foo.yaml  - name: bar    values:    - common.yaml    - bar.yaml

> Alexander Efimov:
нет не просто - у меня релизы на разных чартах и соотвествеено там разная стурктура вельюсов

> Dmitrii Zhiliaev:
ну чтобы их сопоставить вы можете использовать store или   создать файл my-consts.yaml  и внутри foo.yaml readfile my-const.yaml

> Alexander Efimov:
нужно что то типа общих дефайнов шаблонов но так я как понял нельзя - велюс файлы полностью независимо рендарятся

> Dmitrii Zhiliaev:
еще третий способ можете еще select сделать по имени релиза/чарта в файле common.yaml

> Dmitrii Zhiliaev:
но лично мне такой подход не очень нравится.

> Alexander Efimov:
да тоже к этому прихожу но это очень костыльно - так как в кажом файле будет такой общий "импорт" который еще не понятно как сделать полноценно - ведь readfile это  импорт - соотвественно будет какой то конский блок общей обработки явно не напоминающий однострочный импорт - короче это тупик - остаются только костыли через store

> Dmitrii Zhiliaev:
условно   Константы {{ $my := “nginx" }}   {{ if eq .Release.Name “foo” }} image: $my {{ end }}   {{ if eq .Release.Name “bar” }} image:   name: $my }}

> Alexander Efimov:
Не третий не вариант тоже так как в общем логика частного...

> Alexander Efimov:
Только store только хардкор

> Alexander Efimov:
В yml файл получается бедет дублироватся при рендере в каждый релиз маленькая база данных одинаковая в store...

> Roman:
а почему структура валуесов для таких обычных вещей, как регистри, у вас отличается от чарта к чарту? Обычно же принято брать дефолтную структуру валуесов, как у хелма

> Alexander Efimov:
Не у нас а у разных внешних чартов которые используются. И речь не только про реджестри. А принцип общих значений...

> Alexander Efimov:
Было бы конечно удобно иметь общий global Store а не только частные у релизов...

> Roman:
🤔 звучит как возможная фича

> Dmitrii Zhiliaev:
Хмм Звучит нормально 🙂

> Roman:
ну это можно решить шаблонизацией, но глобальная штука лучше

**Comment by zhilyaev** [comment]
I change my mind. Global store is evil.


I recommend use it for `helmwave.yml.tpl`
```yaml
$global = "HelloWorld"

releases:
- name: a
   store:
     greeting: {{ $global }}
       
- name: a
   store:
     greeting: {{ $global }}
```
