### ISSUE TITLE
Add event-based hooks

### ISSUE THREAD

**Issue by r3nic1e** [helmwave/helmwave#412]
Same in helmfile - https://helmfile.readthedocs.io/en/latest/#hooks

Types:

- preapply
- postapply
- predestroy
- postdestroy

We need to understand when to run hooks: after each release or after all releases to finish. I think we can add both global and per-release hooks

**Comment by r3nic1e** [comment]
```go
type hookBody struct {
 script      string
 show_output bool
}

type hook struct {
 pre  []hookBody
 post []hookBody
}

type Hooks struct {
 Rollback  hook
 Uninstall hook
 Pending   string
 Apply     hook
}
```

**Comment by zhilyaev** [comment]
<img width="658" alt="image" src="https://github.com/helmwave/helmwave/assets/4854707/4e1d0401-a1bc-4f36-b226-dd9ea1618f4d">
