### ISSUE TITLE
kubedog for rollback / uninstall scenarios

### ISSUE THREAD

**Issue by zhilyaev** [helmwave/helmwave#414]
**Is your feature request related to a problem? Please describe.**
I wanna track resources while releases are rollbacking and uninstalling.

**Describe the solution you'd like**
Refactor kubedog behavior. Tune kubedog hooks. Pass Kubedog for those operations.

**Comment by samavasi** [comment]
Hi @zhilyaev 
This would be a useful feature , any plan to implement ?

**Comment by r3nic1e** [comment]
@samavasi yeah, I am going to implement. Unfortunately uninstall won't work, only rollback
