### ISSUE TITLE
Support cleartext/non-rendered values files for a release

### ISSUE THREAD

**Issue by samavasi** [helmwave/helmwave#443]
**Is your feature request related to a problem? Please describe.**
Passing values files for a release always seems to render the values yaml with the templating engine, and for some values like kube-prometheus-stack theres content that we pass for alertmanager config that shouldnt even be rendered by helm, and want to read as pure string

**Describe the solution you'd like**
It would be nice if it would be configurable per file/release/global setting to choose `none` as the template engine or based on the filename extension not render a *.yml *.yaml as template (optionally?)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by r3nic1e** [comment]
@samavasi I think we've already done that in previous releases via `render` options for values

https://helmwave.github.io/docs/0.22.x/examples/values-render-flag/

**Comment by samavasi** [comment]
@r3nic1e awesome thanks a lot, Helmwave is really cool!
