### ISSUE TITLE
Ability to deploy and delete deployment(s) based on tags 

### ISSUE THREAD

**Issue by wmariuss** [helmwave/helmwave#457]
**Is your feature request related to a problem? Please describe.**
I do not know if already exists or not, but i could not see any way to delete deployment(s) based on tag(s).
For example, i have some deployments witch are related to infra, this has `infra` as tag and rest of them apps, they have `apps` as tag. I want to remove only the deployments with `apps` tag.

**Comment by wmariuss** [comment]
Also, for `up` commands, i could not see for this commands as well.

**Comment by zhilyaev** [comment]
yep. This command will destroy all releases with tag `apps`
`helmwave down --build -t apps`
