### ISSUE TITLE
Support setting kubectl context per release

### ISSUE THREAD

**Issue by lorf** [helmwave/helmwave#462]
**Is your feature request related to a problem? Please describe.**

Impressed with features I considered using helmwave. But I, currently, don't see how can I install helm releases to different namespaces or clusters using different cluster context for each release.

I'm tasked with setting up a complex app represented as several helm charts that should install in different clusters, split on subapp's security domain and geo location, each subapp in it's own namespace. We have a separate credentials for each cluster and namespace, since the clusters are shared hosting clusters.

**Describe the solution you'd like**

Support setting kubectl context per release in the helmwave.yml

**Describe alternatives you've considered**

I'm trying to acquire cluster wide credentials to workaround installing on the same cluster. But I don't see any workaround using helmwave to install to several clusters.

**Additional context**

**Comment by zhilyaev** [comment]
Yep we have plan for this feature.
