### ISSUE TITLE
chart is local - but got an update and downloading depends

### ISSUE THREAD

**Issue by ocmalex** [helmwave/helmwave#510]
как сделать чтобы при использовании локальных чартов, не происходило постоянной загрузки каждый раз зависимых чартов:

[🙃 aka INFO]: Building repositories...
[🙃 aka INFO]: 🗄 it is local repo
        repository: charts
[🙃 aka INFO]: Building registries...
[🙃 aka INFO]: Building charts...
[🙃 aka INFO]: chart is local, skipping exporting it
        release: keycloak@infra
[🙃 aka INFO]: Building manifests...
[🙃 aka INFO]: Getting updates for unmanaged Helm repositories...
[🙃 aka INFO]: ...Successfully got an update from the "https://charts.bitnami.com/bitnami" chart repository
[🙃 aka INFO]: ...Successfully got an update from the "https://charts.bitnami.com/bitnami" chart repository
[🙃 aka INFO]: Hang tight while we grab the latest from your chart repositories...
[🙃 aka INFO]: ...Successfully got an update from the "main" chart repository
[🙃 aka INFO]: Update Complete. ⎈Happy Helming!⎈
[🙃 aka INFO]: Saving 2 charts
[🙃 aka INFO]: Downloading postgresql from repo https://charts.bitnami.com/bitnami
[🙃 aka INFO]: Downloading common from repo https://charts.bitnami.com/bitnami
[🙃 aka INFO]: Deleting outdated charts
[🙃 aka INFO]: ✅ manifest done

у хелма есть такой ключ:
--skip-refresh     do not refresh the local repository cache
...

Dmitrii Zhiliaev, [9 нояб. 2022 г., 14:24:23 (9 нояб. 2022 г., 14:24:54)]:
Хмм, я конечно перепроверю. Но в предыдущих версиях как раз такая логика и была. Мы изменили повередение для имутабельности helmwave, а сам хелм, неадекватно управляет зависимостями при обновлении чарта.

Но это надо точно упомянуть в ишьуесе, где мы хотим добавть релиз менеджмент для репозитриев и перенести чарты в план.

**Comment by ocmalex** [comment]
Как же больно с этим багом :(
Может есть какие обходные варианты?

Мало того что ждешь кучу времени каждый раз на эти холостые скачивания, так еще через раз
[🙈 aka WARNING]: ❌ can't get dependencies
в лицо :((

Единственный вариант форкать чарты отказываьтся от простой возможности их обновлять и раскорячивать на выпиливание зависимостей ...

**Comment by ocmalex** [comment]
```Makefile
REG_NAME = main
PATH_CHARTS = charts

chart_pull_from_main = 	$(call chart_pull_from_repo,$1,$(REG_NAME))
define chart_pull_from_repo # (chart, repo_name, version) pull from repo 
	$(info helm search: $(shell helm search hub --list-repo-url --max-col-width 70 $1 | grep '$2' | head -c 100))
	$(info untar: $1:$3 from $2)
	rm -rf $(PATH_CHARTS)/$1 ||:
	helm pull $3 --untar -d $(PATH_CHARTS) $2/$1
	$(eval Y := $(PATH_CHARTS)/$1/Chart.yaml)
	mv -f $Y $Y.yml
	yq $Y.yml -o j | jq 'del(.dependencies)' | yq -p j > $Y
	yq .version $Y
endef

define chart_pull # (chart, repo_url, version) pull from url with tmp repo 
	$(info pull: $1:$3 from $2)
	helm repo add $@ $2
	$(call chart_pull_from_repo,$1,$@,$3)
	helm repo remove $@
endef

postgresql: 
	@$(call chart_pull,$@,https://charts.bitnami.com/bitnami)
keycloak:
	@$(call chart_pull,$@,https://charts.bitnami.com/bitnami)

```

**Comment by ocmalex** [comment]
но эти костыли никак не решают проблему условных зависимостей
```YAML
dependencies:
- condition: kubeStateMetrics.enabled
```
:(

**Comment by webmalex** [comment]
:(

**Comment by webmalex** [comment]
> но эти костыли никак не решают проблему условных зависимостей
> 
> ```yaml
> dependencies:
> - condition: kubeStateMetrics.enabled
> ```

временный костыль найден, через ручное выпиливание репозиториев источников:

```
charts/loki-stack/requirements.yaml --- 1/1 --- Text
 1 dependencies:                                                        1 dependencies:                                                       
 2 - name: "loki"                                                       2 - name: "loki"                                                      
 3   condition: loki.enabled                                            3   condition: loki.enabled                                           
 4   repository: "https://grafana.github.io/helm-charts"                . 
 5   version: "^2.15.2"                                                 . 
 6 - name: "promtail"                                                   4 - name: "promtail"                                                  
 7   condition: promtail.enabled                                        5   condition: promtail.enabled                                       
 8   repository: "https://grafana.github.io/helm-charts"                . 
 9   version: "^6.7.4"                                                  . 
```

**Comment by webmalex** [comment]
может кому пригодится костыль:
``` Makefile
PATH_CHARTS = charts
define chart_dependencies_del
	$(info del repositories from: $1)
	cp -n $1 $1.yml ||:
	yq $1.yml -o j | jq 'del(..|.repository?)' | yq -p j > $1
	yq .name $1
endef
charts_dependencies_del: $(PATH_CHARTS)/*/requirements.yaml $(PATH_CHARTS)/*/Chart.yaml
	@$(foreach i, $?, $(call chart_dependencies_del,$i))
```

**Comment by webmalex** [comment]
не помогло:

```
    chart: 
      name: charts/prometheus
      skip_dependency_refresh: true


🙃 aka INFO]: 🗄 it is local repo
        repository: charts
[🙃 aka INFO]: 🔨 Building registries...
[🙃 aka INFO]: 🔨 Building charts...
[🙃 aka INFO]: ❎ chart is local, skipping exporting
        release: prometheus@infra
[🙃 aka INFO]: 🔨 Building manifests...
[🙃 aka INFO]: Saving 4 charts
[🙃 aka INFO]: Downloading kube-state-metrics from repo https://prometheus-community.github.io/helm-charts
[🙃 aka INFO]: Downloading prometheus-node-exporter from repo https://prometheus-community.github.io/helm-charts
[🙃 aka INFO]: Downloading prometheus-pushgateway from repo https://prometheus-community.github.io/helm-charts
[🙃 aka INFO]: Downloading alertmanager from repo https://prometheus-community.github.io/helm-charts
[🙃 aka INFO]: Deleting outdated charts
[🙃 aka INFO]: ✅  manifest done```

**Comment by r3nic1e** [comment]
В 0.29.1 добавили опцию в чарте `skip_dependency_update: true`, которая фиксит эту проблему
