### ISSUE TITLE
diff is inconsistent if order of keys in map is changed

### ISSUE THREAD

**Issue by derbeneviv** [helmwave/helmwave#515]
**Describe the bug**
if order of keys changes in map, the diff can become wrong, showing removal and creation of the same keys even though they did not change  
In the following example env key shows both add and remove, also wome of "args" keys did not change, but are shown in a diff
```
+           env:
+             - name: AWS_DEFAULT_REGION
+               value: eu-west-2
            args:
-             # Generic arguments
-             - --metrics-address=:7979
              - --log-level=info
              - --log-format=text
+             - --interval=1m
              - --events
-             - --domain-filter=***
+             - --source=service
+             - --source=ingress
              - --policy=sync
-             - --provider=aws
              - --registry=txt
-             - --interval=1m
              - --txt-owner-id=test2
              - --txt-prefix=prefix.
-             - --source=service
-             - --source=ingress
-             # AWS arguments
+             - --domain-filter=***
+             - --provider=aws
              - --aws-api-retries=3
              - --aws-zone-type=public
              - --aws-batch-change-size=1000
              - --no-aws-evaluate-target-health
-           env:
-             # AWS environment variables
-             - name: AWS_DEFAULT_REGION
-               value: eu-west-2
```

** General info (please complete the following information):**

- OS: ubuntu 20.04
- Helmwave Version 0.24.2

**To Reproduce**
install bitnami/external-dns chart 6.8.0 https://artifacthub.io/packages/helm/bitnami/external-dns/6.8.0
change chart to https://artifacthub.io/packages/helm/external-dns/external-dns version 1.11.1

run helmwave build

**Expected behavior**
diff shouldn't show changes if data didn't change

**Comment by r3nic1e** [comment]
Done in v0.24.3
