### ISSUE TITLE
Show full release names in dependencies graph

### ISSUE THREAD

**Issue by alexandrovas** [helmwave/helmwave#535]
It would be cool to display full release names in the dependency graph. In the current form, the titles of the releases are unreadable :(
<img width="517" alt="image" src="https://user-images.githubusercontent.com/49055338/211570258-49e92c8c-20af-4ddf-a387-4d1a51825499.png">

**Comment by zhilyaev** [comment]
not stale

**Comment by zhilyaev** [comment]
Yep, I faced this problem too. But we use the extra library. Actually, I  don't want to fork it :)

**Comment by zhilyaev** [comment]
will close in #611
