### ISSUE TITLE
Does not run run upgrade process without values changes

### ISSUE THREAD

**Issue by alexandrovas** [helmwave/helmwave#536]
**Describe the bug**
Helmwave always upgraded release regardless changes in values.

** General info (please complete the following information):**

- OS: linux, macos
- Helmwave Version 0.24.4

**To Reproduce**

1. Install any helm chart with helm hooks (resources with annotation "helm.sh/hook: post-install,post-upgrade")
2. Upgrade deploy with same values
3. See that helmwave creates resources from helm-hooks
4. Wait until the release is updated
5. See that release revision is increased

**Expected behavior**
1. Upgrade should not happened on upgrade with same values.
2. Helm hooks should not created on upgrade with same values.

**Comment by alexandrovas** [comment]
no stale

**Comment by zhilyaev** [comment]
Hi, @alexandrovas! I got your point about "true sync" behavior. But I see some specific situations.


What should helmwave do if you really need to upgrade your release?


1. For example, you have a job that will backup some data. I mean that any upgrade process runs a backup.
- no manifest changes
- no value changes

2. For example, you have a job organized via the current timestamp.

```yaml
annotations:
   deploymentTime: {{ now | date "2006-01-02T15:04:05" }}
```

- manifest changes 
- no value changes


----


Could you describe your receipts for these cases?

**Comment by alexandrovas** [comment]
@zhilyaev Hello! Thanks for you reaction.
I compared native helm behavior with helmwave and I came to the conclusion that I was wrong. Helm behaves absolutely identically when upgrading a release, ie. increases revision and launches jobs.

**Comment by zhilyaev** [comment]
🆗
