### ISSUE TITLE
`helmwave build` requires working stand

### ISSUE THREAD

**Issue by Blobson** [helmwave/helmwave#537]
**Describe the bug**
For now there is no way you can run `helmwave build` with invalid KUBE_CONFIG or if somebody is running `helwave up` in parallel or if you try to test charts with incompatible changes.

With invalid KUBE_CONFIG, you will get an error:
```
[🤬 aka FATAL]: I can't check if release is installed
        release: tp-docs-ui-demo-tp@demo-tp-infra
        error: Kubernetes cluster unreachable: Get "https://172.28.15.241:64434/version": dial tcp 172.28.15.241:64434: connect: connection refused
```

If somebody is updating stand in parallel you'll get:
```
[🤬 aka FATAL]: one of goroutines in waitgroup sent error: 8 errors occurred:
	* failed to fix "session-data-t846-0b9ed@testing-t846-0b9ed-apps" pending status: release is in pending status
	* failed to fix "security-t846-0b9ed@testing-t846-0b9ed-secr" pending status: release is in pending status
	* failed to fix "api-platform-t846-0b9ed@testing-t846-0b9ed-apps" pending status: release is in pending status
	* failed to fix "billing-t846-0b9ed@testing-t846-0b9ed-apps" pending status: release is in pending status
	* failed to fix "authentication-t846-0b9ed@testing-t846-0b9ed-apps" pending status: release is in pending status
	* failed to fix "observability-t846-0b9ed@testing-t846-0b9ed-infra" pending status: release is in pending status
	* failed to fix "appl-t846-0b9ed@testing-t846-0b9ed-apps" pending status: release is in pending status
	* failed to fix "notification-t846-0b9ed@testing-t846-0b9ed-apps" pending status: release is in pending status
```

For incompatible chart changes It fails with:
```
[💩 aka ERROR]: ❌ can't get manifests: failed to upgrade home-page-demo-tp@demo-tp-infra: rendered manifests contain a resource that already exists. Unable to continue with update: Ingress "home-page-demo-tp-dbp-home-page-ing" in namespace "demo-tp-infra" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "home-page-demo-tp"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "demo-tp-infra"
```

Even running with `--diff-mode local` does not help in all of the cases above.

** General info (please complete the following information):**

- OS: verified on Linux and Windows
- Helmwave Version 0.24.3

**To Reproduce**

1. Break contents of your KUBE_CONFIG
2. Try to run `helmwave build --yml --diff-mode local` for any of your Helmwave manifests
3. You will get an error: `I can't check if release is installed`

**Expected behavior**
There should be a way of running `helmwave build` without building diff and making any requests to K8S API. 
It is useful for the sake of linting and verifying Helmwave manifests. 
In our team several engineers can edit Helmwave manifests in parallel and if somebody runs `helmwave up` all others should wait for 20 minutes before testing their changes with linters because they can't get a successful `helmwave build`.

**Comment by zhilyaev** [comment]
will fix in #611
