### ISSUE TITLE
rollback when a helmwave up fails

### ISSUE THREAD

**Issue by ilyesAj** [helmwave/helmwave#559]
**Is your feature request related to a problem? Please describe.**
when helmwave is integrated into GitHub actions and fails once to deploy, all future pipelines will fail with " can't get manifests: failed to fix "xx@xx" pending status: release is in pending status".
you need to manually make `helmwave rollback` to have a consistent state and then rerun the pipeline.

**Describe the solution you'd like**
add a flag to rollback if helmwave up fails. 
like: `helmwave up --kubedog --rollback`
**Describe alternatives you've considered**
catch the error from `helmwave up` and run a rollback as an additional step

**Comment by r3nic1e** [comment]
Hey @ilyesAj, sorry for long wait. There is a `pending_release_strategy` especially for these cases - https://docs.helmwave.app/0.29.x/yaml/#pending_release_strategy

I think there is no need to add an automatic rollback - helm already has `--atomic` and helmwave supports that - https://docs.helmwave.app/0.29.x/yaml/#atomic
