### ISSUE TITLE
helmwave build with `--diff-mode=none` still tries to compare with installed release

### ISSUE THREAD

**Issue by aseychell** [helmwave/helmwave#651]
**Describe the bug**
I would like to build the helmwave plan and manifests without comparing the values to a cluster.  However when using `--diff-mode=none`, helmwave is still trying to compare and sync with the cluster.

** General info (please complete the following information):**

- OS: [macOS]
- Helmwave Version [e.g. 0.29.3]

**To Reproduce**

1. Configure kubectl context so there is no accessible cluster
2. Execute `helmwave build --yml --diff-mode=none`
3. Helmwave will try to perform dry-run: `[🤷 aka DEBUG]: I'll dry-run.`
4. Helmwave will fail `[💩 aka ERROR]: ❌ can't get manifests: failed with dry-run .....`

**Expected behavior**
Being able to call helmwave build without a running cluster (similar to `helm template`)

**Comment by zhilyaev** [comment]
You should use offline_kube_version.
Dry run option always proceeds.
