### ISSUE TITLE
Support for importing from helmfile.yaml

### ISSUE THREAD

**Issue by felipecrs** [helmwave/helmwave#692]
**Is your feature request related to a problem? Please describe.**
I work in a big organization with several teams working on different projects. We have adopted Helmfile across many teams to ease installation of their Helm charts, and each team maintains their own `helmfile.yaml` which we can use as build blocks to build the final list of releases to deploy.

I'm eager to switch from Helmfile to Helmwave (especially because of enhanced logs), but I can't convince my entire organization to do so, not at this moment.

**Describe the solution you'd like**
It would be great if Helmwave could read existing `helmfile.yaml` files and transform into Helmwave's own configuration. From what I noticed, `helmfile.yaml` has everything that Helmwave would need to know about a release to be able to deploy it.

Maybe helmfile exposes some golang library for reading `helmfile.yaml`, but even in worst case, I don't think it should be too hard to implement a parser that translates `helmfile.yaml` to helmwave.

**Describe alternatives you've considered**
The only alternative to it would be to convince everyone to use Helmwave, which is mostly impossible in my case.

**Additional context**
None.

**Comment by r3nic1e** [comment]
Hey, @felipecrs! My ideas on that:

1. We will have to keep up with helmfile updates and adapt them to helmwave. It's not the way I as a maintainer want the project to follow
2. There are a lot of things that are completely different in helmfile and helmwave. e.g. `set` (or inline values) should be converted into separate values file but templating them may be broken (e.g. there is no alternative for `{{ .Namespace }}` in helmwave)
3. Helmfile has support for some helm plugins while helmwave doesn't (e.g. `helm-secrets`).
4. It's relatively easy to convert basic functionality that exists both in helmfile and helmwave. And it's also easy to do that manually without any converter

**Comment by felipecrs** [comment]
Yes, this is 100% fair. Maybe if there was a way to delegate the `helmfile.yaml` expansion to `helmfile` itself, even if this would mean to have `helmfile` installed, we could address 2 and 3.

In fact, `helmfile build --quiet --embed-values` could probably be used to ensure all `helmfile` templates are expanded and sanitized, outputting a static `yaml` file to read from.

1 would be done at best effort. Many parts of `helmfile.yaml` have been there for years without changing. I believe it would be even acceptable to only provide support for basic functionality as pointed in 4.

As helmfile approaches v1, the risk of being outdated tends to diminish as well.

---

Nevertheless, I totally understand 1 from a maintainer's point of view having to maintain such compatibility layer. Any ideas on how to offload such responsibility (helmwave plugins?) would be cool.

**Comment by zhilyaev** [comment]
it would be better to make a migration guide in the form of an article

**Comment by felipecrs** [comment]
Yeah, that would certainly help too.

**Comment by r3nic1e** [comment]
There is a new page in docs regarding migration - https://docs.helmwave.app/0.32.x/examples/helmfile-migration/

**Comment by felipecrs** [comment]
Thanks a lot. If you really have no plans to implement "reading from helmfile.yaml" capability, please close this issue.
