### ISSUE TITLE
wait: true doesn't work during deletion

### ISSUE THREAD

**Issue by AlexeyStolyarov** [helmwave/helmwave#697]
**Describe the bug**
helmwave doesn't wait till an installed resource has been deleted. 
even with `wait: true` option.

** General info (please complete the following information):**

- OS: linux
- helmwave version 0.30.1

**To Reproduce**
1.  create a helm chart with namespace manifest.
2. install it using `helmwave up`
3. uninstall it using `helmwave down`
4. install this chart again without having a pause

**Expected behavior**
with enabled `wait` option helmwave should wait till the installed release will have been uninstalled.

**Screenshots / Stdout**
[💩 aka ERROR]: ❌
	release: svbo-scheduler@rnd-svbo-night-build-dev
	error: failed to install "svbo-scheduler@rnd-svbo-night-build-dev": create: failed to create: secrets "sh.helm.release.v1.svbo-scheduler.v1" is forbidden: unable to create new content in namespace rnd-svbo-night-build-dev because it is being terminated
[🤬 aka FATAL]: one of goroutines in waitgroup sent error: 1 error occurred:
	* failed to install "svbo-scheduler@rnd-svbo-night-build-dev": create: failed to create: secrets "sh.helm.release.v1.svbo-scheduler.v1" is forbidden: unable to create new content in namespace rnd-svbo-night-build-dev because it is being terminated

**Comment by r3nic1e** [comment]
We should prepare helm action with copying release parameters [here](https://github.com/helmwave/helmwave/blob/main/pkg/release/uninstall.go#L28) just like for [install and upgrade](https://github.com/helmwave/helmwave/blob/main/pkg/release/config.go#L69)
