### ISSUE TITLE
helm/NOTES.txt breaks helmwave output

### ISSUE THREAD

**Issue by AlexeyStolyarov** [helmwave/helmwave#707]
**Describe the bug**
when show Notes.txt from a helmchart it breaks HelmWave output

** General info (please complete the following information):**

- OS: linux
- Helmwave Version 0.31.1

**To Reproduce**
run `helmwave up --build -yml` in a gitlab's pipeline

**Expected behavior**
block rendered from Notes.txt doesn't break output. 

**Screenshots / Stdout**
![image](https://github.com/helmwave/helmwave/assets/15113474/046ac319-3ba5-4fab-9ea4-13a61ab45c10)

**Comment by zhilyaev** [comment]
logger put info field asynchronously

**Comment by r3nic1e** [comment]
Hey, @AlexeyStolyarov, it's kinda expected in our logger formatter to see fields (e.g. `release`) under multiline output. On my localhost it always shows fields under the message
<img width="906" alt="image" src="https://github.com/helmwave/helmwave/assets/4354690/6801c4a2-d954-4366-a7b5-67bc6c5f7d4a">

So I don't think that's an issue at all.
