### ISSUE TITLE
Support for ANSI colors in helm/NOTES.TXT

### ISSUE THREAD

**Issue by AlexeyStolyarov** [helmwave/helmwave#726]
It would be nice to have well printed helm info which is easy to distinguish from the rest helmwave output.
It makes bigger sense when you use helmwave in a pipeline ( e.g. gitlab) that have a lot of output and it is quite hart to see the crux of the actions.

As an option suppose supporting ANSI colors in helm/notes.txt.
The solution is entirely up to you though.

**Comment by r3nic1e** [comment]
What do you mean by "helm info"?

**Comment by r3nic1e** [comment]
It is supported
