### ISSUE TITLE
check if docker images are reacheble

### ISSUE THREAD

**Issue by AlexeyStolyarov** [helmwave/helmwave#748]
if would be great if Helm could check all helm images whether they are exist.

e.g.

```
helmwave --validate-images
```

**Comment by AlexeyStolyarov** [comment]
> You mean OCI images? Why do you need that?
yep.
Sometimes deployment takes really long time and it's inconvenient when you find your typofix after a half hour after  deployment has done.

What if we could test that deployment wont fail before committing it?

**Comment by r3nic1e** [comment]
Okay, so you mean images used for containers in pods, not OCI helm charts images.

I don't think that is a job for a deploy tool. It will require:
- parsing and supporting numerous of kubernetes resources that contain image so helmwave will be bound to specific k8s versions
- leave all CRDs unsupported

So this feature will be both incomplete and handle only one specific human-provided error leaving all other unfixed.

Helmwave generates manifests during `helmwave build` so you can validate images on your own.
