### ISSUE TITLE
Add support to use dotenv file

### ISSUE THREAD

**Issue by anuragagarwal561994** [helmwave/helmwave#750]
**Is your feature request related to a problem? Please describe.**
Since most of the flags are backed by env variables it will be easier to use and commit them with dotenv file

**Describe the solution you'd like**
Using dotenv file to read env variables

I have tried using tools such as direnv, autoenv, zsh configurations etc. but to be honest it is very cumbersome to configure and deal with them, although they would work but the biggest questions for such tools is that if we have configured some envs when a user enters a directory how will we unset them when user exits the directory and that does create an .env mess. Hence a better solution is always to adopt the application itself to add support for reading .env files.

**Comment by anuragagarwal561994** [comment]
Can we keep this open since I have made the changes for this as well in the MR

**Comment by anuragagarwal561994** [comment]
Oh I just checked that a label for wontfix is placed, is there a specific reason for the same?

**Comment by r3nic1e** [comment]
Released in [0.33.0](https://github.com/helmwave/helmwave/releases/tag/v0.33.0)
