### ISSUE TITLE
Helmwave should uninstall in reverse order of dependency

### ISSUE THREAD

**Issue by anuragagarwal561994** [helmwave/helmwave#752]
**Is your feature request related to a problem? Please describe.**
Currently helmwave deploys and respects `depends_on` but the `down` command doesn't respect depends_on and wait as well.

We should ideally destroy the resources in the reverse order that they were created, I have a usecase where one of my release is creating a storage class and provisioner, my another release is trying to add a PV & PVC for this storage class. But when the release is destroyed, before the PV and PVCs are deleted the release which is bringing the storage class is uninstalled first which deletes the PVC but PV is stuck in Released state, also the provisioner is also stuck because of the PVC and doesn't uninstall.

**Describe the solution you'd like**
We should use depends_on data while bringing down the release.

Here we can also provide support for `wait` while uninstalling, not sure if it was already present earlier in helm but now helm supports it, also it has `cascade` parameter which is can also be supported so one can ensure a dependent release is completely removed before moving forward to another release.

**Comment by r3nic1e** [comment]
Support for `wait` during uninstall was released in 0.31.1 and should be working (if `wait: true` is provided for the release)

Dependencies for uninstalling should be used, nice catch!
