### ISSUE TITLE
Add support for helmwave.yaml filename instead of helmwave.yml

### ISSUE THREAD

**Issue by MurzNN** [helmwave/helmwave#791]
**Is your feature request related to a problem? Please describe.**
The YAML standard recommends using ".yaml" extension for YAML files, instead of the shortened ".yml": https://yaml.org/faq.html

But if I use `helmwave.yaml` - I got an error:
```
[🤬 aka FATAL]: failed to read plan file helmwave.yml: open helmwave.yml: no such file or directory
```

**Describe the solution you'd like**
Please add support for ".yaml" extension too.

**Comment by zhilyaev** [comment]
```bash
export HELMWAVE_YAML=helmwave.yaml
helmwave build
```

welcome!

**Comment by r3nic1e** [comment]
It is supported - https://docs.helmwave.app/0.32.x/cli/#-file. Extension doesn't matter
