### ISSUE TITLE
Can't create files on Windows OS

### ISSUE THREAD

**Issue by sasha2002** [helmwave/helmwave#809]
**Describe the bug**
[🙃 aka INFO]: 🔨 Building charts...
[🤬 aka FATAL]: CreateFile .\oci:\registry-1.docker.io\bitnamicharts\nats: The filename, directory name, or volume label syntax is incorrect.

** General info (please complete the following information):**

- OS: [e.g. linux, windows, macOS]
Windows 11 Pro
- Helmwave Version [e.g. 0.18.0]
0.33.0 (Latest)

**To Reproduce**
Using [guide](https://docs.helmwave.app/0.33.x/examples/quick-start/) created file and try to build

**Expected behavior**

Have Plan as it is described
`This step generates [plan](https://docs.helmwave.app/0.33.x/cli/#build)`

**Screenshots / Stdout**
If applicable, add screenshots / stdout logs to help explain your problem.

`
> helmwave build
[🙃 aka INFO]: 🔨 Building releases...
[🙃 aka INFO]: 🔨 Building values...
[🙃 aka INFO]: 🔨 no values provided
        release: b@my-namespace
[🙃 aka INFO]: 🔨 no values provided
        release: a@my-namespace
[🙃 aka INFO]: 🔨 Building repositories...
[🙃 aka INFO]: 🔨 Building registries...
[🙃 aka INFO]: 🗄 registry has been added to the plan
        registry: registry-1.docker.io
[🙃 aka INFO]: 🔨 Building charts...
[🤬 aka FATAL]: CreateFile .\oci:\registry-1.docker.io\bitnamicharts\nats: The filename, directory name, or volume label syntax is incorrect.
`

**Additional context**
Some better examples how to create this file and how to maintain cluster after deployment

**Comment by doonydoo** [comment]
i have same issue

**Comment by zhilyaev** [comment]
I don't want to play the "correct-paths-game" on the Windows OS family. I recommend everyone use WSL.
Feel free to reopen this issue if you have any concerns about it.
