### ISSUE TITLE
Invalid JSON Schema

### ISSUE THREAD

**Issue by mhkarimi1383** [helmwave/helmwave#834]
**Describe the bug**
Getting invalid schema error while adding it to schema store neovim plugin

**General info (please complete the following information):**

- OS: linux
- helmwave version 0.34.0

**To Reproduce**

Configure neovim yamlls like that

```lua
  yamlls_config = {
    yaml = {
      schemaStore = {
        enable = false,
        url = '',
      },
      schemas = require('schemastore').yaml.schemas({
        extra = {
          url = "https://github.com/helmwave/helmwave/releases/latest/download/schema.json",
          name = "Helmwave",
          description = "Helmwave configuration",
          fileMatch = "helmwave.yml",
        }
      }),
    },
  },
```

**Expected behavior**
A working json schema

**Screenshots / Stdout**

```
 ■ Schema 'schema.json' is not valid:  /properties/monitors/items/properties/total_timeout/oneOf/1/type : must be equal to one of the allowed values  /properties/monitors/items/properties/total_timeout/oneOf/1/type : must be array  /properties/monitors/items/properties/total_timeout/oneOf/1/type : must match a schema in anyOf  /properties/monitors/items : must be array  /properties/monitors/items : must match a schema in anyOf
```

**Additional context**

**Comment by mhkarimi1383** [comment]
@zhilyaev
Hi, any updates on this problem?

**Comment by zhilyaev** [comment]
<img width="750" alt="image" src="https://github.com/helmwave/helmwave/assets/4854707/3cac4dda-65e9-47be-ab21-8d918fc922e7">

**Comment by mhkarimi1383** [comment]
> I have never faced with Neovim. Could you ask the community about the Neovim project? 
> 
> And if NeoVim provides https://www.schemastore.org.  You don't need to specify this.

NeoVim uses the same thing

But I don't know why I'm having this problem, only with this jsonschema

**Comment by mhkarimi1383** [comment]
here is my `settings.json`

```json
{
  "yaml.schemas": {
    "https://github.com/helmwave/helmwave/releases/latest/download/schema.json": "file:///home/karimi/Projects/parmin/signal/applications/metabase/helmwave.yml"
  }
}
```

**Comment by r3nic1e** [comment]
@zhilyaev The provided error is weird but I found out the root cause.

For some fields we have `type=int` while jsonschema has type `integer`. So we need to go through all jsonschema definitions and change `int` to `integer`

**Comment by zhilyaev** [comment]
#846 well

**Comment by mhkarimi1383** [comment]
Fixed 😁

**Comment by mhkarimi1383** [comment]
@zhilyaev 
I have another problem that when I use string values for values or depends on params I get validation errors, Also sometimes objects are getting errors too.

**Comment by mhkarimi1383** [comment]
Incorrect type. Expected "string | object(Values of the release)".yaml-schema: Values of the release
Incorrect type. Expected "object(Values of the release)".yaml-schema: Values of the release
