### ISSUE TITLE
Add AppVersion & Version switches before build

### ISSUE THREAD

**Issue by IvanRezv** [helmwave/helmwave#842]
Hi!

**Is your feature request related to a problem? Please describe.**
I need a flag for AppVersion and version switching, every Deploy application process, now i'm do it with:

```bash
sed -i 's/version:.*/version: "'${CURRENT_RELEASE_VERSION}'"/g' ${HELM_CHART_PATH}/Chart.yaml
sed -i 's/appVersion:.*/appVersion: "'${FINAL_APPLICATION_VERSION}'"/g' ${HELM_CHART_PATH}/Chart.yaml
```

**Describe the solution you'd like**

```bash
helmwave build --version 22.0.0 --app-version 55-SNAPSHOT
```

**Describe alternatives you've considered**
Helm can do it only on package.

```bash
helm package --app-version 55-SNAPSHOT --version 22.0.0
```

**Comment by zhilyaev** [comment]
Not related to helmwave
