### ISSUE TITLE
Diff mode doesn't disable interaction with k8s

### ISSUE THREAD

**Issue by KaygorodovIS** [helmwave/helmwave#886]
**Describe the bug**
Diff mode flag has no effect on behavior

**General info (please complete the following information):**

- OS: linux, docker image diamon/helmwave:0.32.1
- Helmwave Version 0.32.1

**To Reproduce**
- Set `HELMWAVE_DIFF_MODE` to `local` or `none`
- Run `helmwave build`
- See the following warnings in the logs
```
W0514 14:01:04.347045    2191 warnings.go:70] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
W0514 14:01:04.349341    2191 warnings.go:70] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
W0514 14:01:04.353740    2191 warnings.go:70] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
W0514 14:01:04.364872    2191 warnings.go:70] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
W0514 14:01:04.454007    2191 warnings.go:70] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
```
The warnings themselves are related to k8s settings (update k8s from 1.26 to 1.28) but indicate that k8s is being accessed

**Comment by r3nic1e** [comment]
Diff mode doesn't disable interaction with k8s. It just tunes whether to check diff with another release and how.

I think you are looking for [`offline_kube_version`](https://docs.helmwave.app/0.36.x/yaml/#offline_kube_version) together with `diff-mode=none`.

**Comment by KaygorodovIS** [comment]
It's work fo me. thx
