### ISSUE TITLE
Lifecycle hook doesn't work at release scope

### ISSUE THREAD

**Issue by zhilyaev** [helmwave/helmwave#935]
**Describe the bug**

**General info (please complete the following information):**

- OS: macOS
- Helmwave Version 0.38.0

**To Reproduce**

**Expected behavior**
https://docs.helmwave.app/0.38.x/examples/lifecycle/ 

**Screenshots / Stdout**
If applicable, add screenshots / stdout logs to help explain your problem

**Comment by Vigilans** [comment]
Yes, I have a pre_build script to download the chart from github source code by release tag. 

This hook works when placed in global level, but not in per-release level. This is not desired, as the script will always be executed even if the corresponding release is disabled by helmwave tag.
```
lifecycle:
  pre_build:
    - scripts/github-ref.sh https://github.com/rancher/local-path-provisioner v0.0.28 */deploy/chart/local-path-provisioner
```
