### ISSUE TITLE
Kubecontext has too restrict regexp

### ISSUE THREAD

**Issue by marre** [helmwave/helmwave#939]
CI pipelines using the GitLab kubernetes agent uses context names like `path/to/agent/project:agent-name` and this breaks helmwave-0.38.0.

Error message:
```
[💩 aka ERROR]: failed to generate valid uniqname
	context: path/to/agent/project:agent-name
	error: failed to validate uniqname: mysql@mysql-operator@path/to/agent/project:agent-name, problem with: path/to/agent/project:agent-name
```

My guess is that this regexp is too retrictive:

https://github.com/helmwave/helmwave/blame/538076f4bc6ee387cc53d2a08783c53d1a007a83/pkg/release/uniqname/uniqname.go#L14
```
	KubecontextRegexp = regexp.MustCompile("^[a-z0-9]([-a-z0-9_]*[a-z0-9])?$")
```

**Comment by zhilyaev** [comment]
Thank you for the issue!
Yes, it's too much.
We should do it more flexibly

**Comment by zhilyaev** [comment]
@marre Could you suggest a new regexp for kubecontext?

**Comment by zhilyaev** [comment]
I am not sure, but may this one become the answer `^[a-zA-Z0-9]([a-zA-Z0-9._-]*[a-zA-Z0-9])?$`

- `^[a-zA-Z0-9]` — The name starts with a letter or a digit.
- `[a-zA-Z0-9._-]` — Allows letters, digits, dots, hyphens, and underscores in the middle.
- `[a-zA-Z0-9])?$` —  The name must end with a letter or a digit.

**Comment by marre** [comment]
It may contain ’/’ as well

**Comment by marre** [comment]
So perhaps:
`^[a-zA-Z0-9]([a-zA-Z0-9._\/\:-]*[a-zA-Z0-9])?$`

I'm a bit unsure if the / and : needs to be escaped in golang though.

**Comment by zhilyaev** [comment]
Wow, is it possible for a kubeContext to contain colons and slashes?

**Comment by stickyb1t** [comment]
hi @zhilyaev 
On version 0.39.0 the problem is reproduced
`[💩 aka ERROR]: failed to generate valid uniqname
        error: failed to validate uniqname: apim-istio-ingress-resources@istio-system@gate.k8s-stage, problem with: gate.k8s-stage
        release: apim-istio-ingress-resources@istio-system@gate.k8s-stage
        name: apim-istio-ingress-resources
        namespace: istio-system
        context: gate.k8s-stage
`

**Comment by zhilyaev** [comment]
#959

**Comment by stickyb1t** [comment]
> #959

thanks, it works
